networks:
  frontend:
    name: frontend

volumes:
  traefik_acme:
    name: traefik_acme

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - frontend

  traefik:
    image: "traefik:v3"
    container_name: "traefik"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"    # Traefik precisa processar requests rápido
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./traefik_logs:/var/log/traefik"
    networks:
      - frontend
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    command:
      - "--ping=true" # <--- 1. NECESSÁRIO PARA O HEALTHCHECK
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.bouncer.version=v1.4.6"
# para ver mais dados no log, comentar a linha acima e descomentar as 4 abaixo.
#      - --log.level=DEBUG
#      - --accesslog.format=json # Formato JSON detalha melhor a duração
#      - --accesslog.fields.headers.defaultmode=keep # Mostra os headers

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=secure-auth,crowdsec-check"
      # Middleware de autenticação
      - "traefik.http.middlewares.secure-auth.basicauth.users=${BASIC_AUTH}"
      # Repassa para todos os serviços informação de acesso por HTTPS
      - "traefik.http.middlewares.ssl-header.headers.customrequestheaders.X-Forwarded-Proto=https"
      # Middleware do bouncer crowdsec
      - "traefik.http.middlewares.crowdsec-check.plugin.bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec-check.plugin.bouncer.updateIntervalSeconds=60"
      - "traefik.http.middlewares.crowdsec-check.plugin.bouncer.crowdseclapischeme=http"
      - "traefik.http.middlewares.crowdsec-check.plugin.bouncer.crowdseclapihost=crowdsec:8080"
      - "traefik.http.middlewares.crowdsec-check.plugin.bouncer.crowdseclapikey=${TOKEN_BOUNCER}"


  error-pages:
    image: tarampampam/error-pages:latest
    container_name: error-pages
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.1"
    networks:
      - frontend
    environment:
      - TEMPLATE_NAME=lost-in-space # Opções: ghost, matrix, lost-in-space, connection, l7-light
      - SHOW_DETAILS=false
    labels:
      - "traefik.enable=true"
      # Regra: Pega QUALQUER host
      - "traefik.http.routers.catchall.rule=PathPrefix(`/`)"
      - "traefik.http.routers.catchall.entrypoints=web"
      # Prioridade: 1 (A Mínima possível).
      - "traefik.http.routers.catchall.priority=1"
      - "traefik.http.routers.catchall.service=error-pages"
      - "traefik.http.services.error-pages.loadbalancer.server.port=8080"

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.75"
    networks:
      - frontend
    healthcheck:
      test: [ "CMD", "cscli", "lapi", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - GID=1000
      - BOUNCER_KEY_TRAEFIK=${TOKEN_BOUNCER}
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve # Regras prontas para Traefik
    volumes:
      - ./crowdsec-db:/var/lib/crowdsec/data       # Banco de dados persistente
      - ./crowdsec-config:/etc/crowdsec            # Configurações
      - ./traefik_logs:/var/log/traefik:ro         # Lê os logs do Traefik (Read Only)
